config/routes.rb
Rails.application.routes.draw do
  
  resources :jobcomments
  resources :jobposts
  resources :profiles
  resources :talkresps
  resources :projtalks
  
  post'/sendAttachments' => 'projects#sendAttachment'
  get '/getFriends' => 'users#getfriends'
  post '/send_sms' => 'twilio#send_sms'
  resources :deadlines
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :taskmemberships
  resources :projectmemberships
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users
  resources :friendships
  resources :projects
  resources :tasks
  resources :subtasks
  resources :comments    
  get 'page/index'
  root 'rails_admin/main#dashboard'


  resources :users do
    resources :friendships
    resources :projects do
      resources :tasks do
        resources :subtasks do
          resources :comments
        end
      end
    end
  end


end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :task
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"

end
		

app/models/jobcomment.rb
class Jobcomment < ActiveRecord::Base
	belongs_to :user
	belongs_to :jobpost
end

app/models/jobpost.rb
class Jobpost < ActiveRecord::Base
	belongs_to :user
	has_many :jobcomments
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
 	has_many :friend_requests, -> { where(friendships: {approved: false}) }, :class_name => "Friendship", :foreign_key => "friend_id"
  
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks, dependent: :destroy
	belongs_to :user


  	has_many :projectmemberships, dependent: :destroy
	has_many :pmembers, :through => :projectmemberships
	has_many :projtalks, dependent: :destroy
end

app/models/projectlog.rb
class Projectlog < ActiveRecord::Base
	belongs_to :project
	belongs_to :user
end

app/models/projtalk.rb
class Projtalk < ActiveRecord::Base
	belongs_to :user
	belongs_to :project
	has_many :talkresps, dependent: :destroy
end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
	belongs_to :task
	belongs_to :project

end

app/models/talkresp.rb
class Talkresp < ActiveRecord::Base
	belongs_to :projtalk
	belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :subtasks, dependent: :destroy
	has_many :comments, dependent: :destroy
	belongs_to :project
	belongs_to :user


	has_many :taskmemberships, dependent: :destroy
	has_many :tmembers, :through => :taskmemberships
end

app/models/taskmembership.rb
class Taskmembership < ActiveRecord::Base
	belongs_to :user
	belongs_to :task, :class_name => "Task"
	belongs_to :tmember, :class_name => "User"
end

app/models/user.rb
class User < ActiveRecord::Base
has_secure_password
  validates :name,
            presence: true
  validates :phonenumber,
            presence: true
  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }
  def to_s
    "#{name} #{phonenumber}"
  end

 
  has_one :profile
  has_many :projects, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy
  

  #has_many :friendships, dependent: :destroy
  #has_many :friends, :through => :friendships, dependent: :destroy
  #has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id", dependent: :destroy
  #has_many :inverse_friends, :through => :inverse_friendships, :source => :user, dependent: :destroy

  has_many :friendships, dependent: :destroy
  has_many :passive_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
 
  has_many :friends,-> { where(friendships: { approved: true}) }, :through => (:friendships && :passive_friendships), :source => (:friend && :user) 
  has_many :active_friends, -> { where(friendships: { approved: true}) }, :through => :friendships, :source => :friend 
  has_many :passive_friends, -> { where(friendships: { approved: true}) }, :through => :passive_friendships, :source => :user
  has_many :pending_friends, -> { where(friendships: { approved: false}) }, :through => :friendships, :source => :friend
  
  has_many :requested_friendships, -> { where(friendships: { approved: false}) }, :through => :passive_friendships, :source => :user
  has_many :friend_requests, -> { where(friendships: {approved: false}) }, :class_name => "Friendship", :foreign_key => "friend_id"
  
  #has_many :friend_gets, -> { where(friendships: {approved: false && approved: true}) }, :class_name => "Friendship", :foreign_key => "friend_id"
  
  def friends
    active_friends | passive_friends
  end

  has_many :projectmemberships,dependent: :destroy
  has_many :joined_projectmemberships, :class_name => "Projectmembership", :foreign_key => "pmember_id"
  has_many :joined_projects, :through => :joined_projectmemberships, :source => :project

  has_many :projtalks, dependent: :destroy
  has_many :talkresps, dependent: :destroy

  has_many :jobposts, dependent: :destroy
  has_many :jobcomments, dependent: :destroy

end



#has_many :friendships
#has_many :friends, through: :friendships, source: :user
#has_many :active_friends, -> { where(friendships: {approved: true, active: true}) }, :through => :friendships
#has_many :passive_friends, -> {where(friendships: {approved: true, active: false}) }, :through => :friendships

app/controllers/projtalks_controller.rb
class ProjtalksController < ApplicationController
  before_action :set_projtalk, only: [:show, :edit, :update, :destroy]

  # GET /projtalks
  # GET /projtalks.json
  def index
    @projtalks = Projtalk.all
  end

  # GET /projtalks/1
  # GET /projtalks/1.json
  def show
    @projtalk = Projtalk.find(params[:id])
  end

  # GET /projtalks/new
  def new
    @projtalk = Projtalk.new
  end

  # GET /projtalks/1/edit
  def edit
  end

  # POST /projtalks
  # POST /projtalks.json
  def create
    @projtalk = Projtalk.new(projtalk_params)
      if @projtalk.save
 render json: {status: :success, projtalk: @projtalk}
      else
        render json: {status: :failed, project: @projtalk}
      end
  
  end

  # PATCH/PUT /projtalks/1
  # PATCH/PUT /projtalks/1.json
  def update
      if @projtalk.update(projtalk_params)
 render json: {status: :success, projtalk: @projtalk}
      else
        render json: {status: :failed, project: @projtalk}      end
  end

  # DELETE /projtalks/1
  # DELETE /projtalks/1.json
  def destroy
    @projtalk.destroy
    respond_to do |format|
      format.html { redirect_to projtalks_url, notice: 'Projtalk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projtalk
      @projtalk = Projtalk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projtalk_params
      params.require(:projtalk).permit(:user_id, :project_id, :name)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/jobposts_helper.rb
module JobpostsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/projtalks_helper.rb
module ProjtalksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/twilio_helper.rb
module TwilioHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projtalks/_form.html.erb
<%= form_for(@projtalk) do |f| %>
  <% if @projtalk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projtalk.errors.count, "error") %> prohibited this projtalk from being saved:</h2>

      <ul>
      <% @projtalk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projtalks/edit.html.erb
<h1>Editing Projtalk</h1>

<%= render 'form' %>

<%= link_to 'Show', @projtalk %> |
<%= link_to 'Back', projtalks_path %>

app/views/projtalks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projtalks</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Project</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projtalks.each do |projtalk| %>
      <tr>
        <td><%= projtalk.user_id %></td>
        <td><%= projtalk.project_id %></td>
        <td><%= projtalk.name %></td>
        <td><%= link_to 'Show', projtalk %></td>
        <td><%= link_to 'Edit', edit_projtalk_path(projtalk) %></td>
        <td><%= link_to 'Destroy', projtalk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Projtalk', new_projtalk_path %>

app/views/projtalks/new.html.erb
<h1>New Projtalk</h1>

<%= render 'form' %>

<%= link_to 'Back', projtalks_path %>

app/views/projtalks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @projtalk.user_id %>
</p>

<p>
  <strong>Project:</strong>
  <%= @projtalk.project_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @projtalk.name %>
</p>

<%= link_to 'Edit', edit_projtalk_path(@projtalk) %> |
<%= link_to 'Back', projtalks_path %>